.\" Manpage for ramics.
.\" Contact imogen@sanbi.ac.za to correct errors or typos.
.TH man 8 "31 July 2013" "1.0b" "ramics man page"
.SH NAME
ramics \- Run the RAMICS sequence alignment algorithm.
.SH SYNOPSIS
\fBramics\fR [OPTIONS] \fB\-i\fR INPUT_FILE \fB\-r\fR REFERENCE_FILE \fB\-o\fR OUTPUT_FILE.EXT [\fB-n\fR ITERATIONS]
.SH DESCRIPTION
\fBRAMICS\fR is a hidden Markov model reference mapper, designed to align coding and non-coding DNA to a reference sequence.  By default, RAMICS assumes DNA is coding and Sanger-sequenced.  
Options allow the user to specify the sequencing platform used for more accurate alignment.  
RAMICS can also be set to \fBtraining\fR mode, where it will iteratively refine the profile hidden Markov model associated with the reference sequence to the profile of the query sequences aligned to it.
.SH OPTIONS
.TP
.BR \-i ", " \-\-input " " \fIINPUT_FILE\fR
Path to FASTA/FASTQ formatted input file.
.TP
.BR \-r ", " \-\-reference " " \fIREFERENCE_FILE\fR
Path to FASTA formatted reference file.
.TP
.BR \-o ", " \-\-output " " \fIOUTPUT_FILE\fR
Path to FASTA formatted reference file.
.TP
.BR \-n ", " \-\-iterations " " \fIITERATIONS\fR
The number of training iterations performed to train the profile hidden Markov model - should be higher for more divergent sequences.
.TP
.BR \-\-non-coding
The DNA to be aligned does not code for an amino acid sequence.
.TP
.BR  \-\-coding
The DNA to be aligned codes for an amino acid sequence (on by default).
.TP
.BR  \-\-clean
Assume the data is entirely free of spurious frame shifts, and allow codon-sized gaps only (overrides the sequencing machine set).
.TP
.BR \-c ", " \-\-consensus-count " " \fICOUNT\fR
Generate consensus sequences with a count of contributing sequences lower than than \fICOUNT\fR.  Output will be written to \fIOUTPUT_FILE\fR.consensus.\fIEXT\fR.
.TP
.BR \-s ", " \-\-amplicon-start " " \fIAMPLICON_START\fR
Cut the reference sequence starting at a particular \fIcodon\fR position and align only against a given amplicon.  Mutations will still be called w.r.t. the full sequence. (Must be used with {\fB-e\fR | \fB--end-amplicon}.
.TP
.BR \-e ", " \-\-amplicon-end " " \fIAMPLICON_END\fR
Cut the reference sequence ending at a particular \fIcodon\fR position and align only against a given amplicon.  Mutations will still be called w.r.t. the full sequence. (Must be used with {\fB-s\fR | \fB--start-amplicon}.
.TP
.BR \-f ", " \-\-full-length
Print only sequences that cover the full length of a sliced amplicon (or the full length of the reference sequence if no amplicon is sliced). 
.TP
.BR \-w ", " \-\-print-codons
Print an alignment, printed in a separate file labelled \fIOUTPUT_FILE\fR.codons.\fIEXT\fR, that widens every single gap to the size of a codon, preserving the open reading frame in codon space.  

.TP
.BR \-y ", " \-\-print-cleaned
Print an alignment, printed in a separate file labelled \fIOUTPUT_FILE\fR.cleaned.\fIEXT\fR, that does not contain single, spurious insertions.  \fBCAUTION\fR: This will remove columns from the alignment that contain single insertions under the assumption that they are sequencing errors.  Your output sequences will not be the same as your input sequences.
.TP
.BR \-m ", " \-\-print-mutations
Print amino acids in a new format, FASTM, to the file \fBOUTPUT_FILE\fR.fastm.  The format is of the type:
 
>SEQUENCE_NAME
1X, 2X, 3X, 4X, 5P, 6P, 6iTP, 7G, 8d

where \fBi\fR indicates an insertion at that position, and \fBd\fR indicates a deletion.  Positions are called with respect to the full sequence, even if an amplicon has been sliced from it. This format is useful for downstream analysis and is tailored particularly for entry into the Sierra drug-resistance mutation calling algorithm \fBHIVdb\fR.  Codons with an average quality score below a given threshold, (19 by default), are called as \fBX\fR.
.TP
.BR \-t ", " \-\-quality-threshold " " \fIQUALITY_SCORE\fR
When paired with \fB--print-mutations\fR, this setting replaces codons with an average quality score of less than a given threshold with an amino acid call of \fBX\fR.
.TP
.BR  \-g ", " \-\-gap " " \fIGAP_PENALTY\fR
Set the codon gap penalty for coding DNA, or the nucleotide gap penalty for non-coding DNA.  Default is -10 for non-coding nucleotides and -30 for codons.  Must be negative to produce sensible alignments.
.TP
.BR  \-x ", " \-\-extension " " \fIEXTENSION_PENALTY\fR
Set the codon gap extension penalty for coding DNA, or the nucleotide gap extension penalty for non-coding DNA.  Default is -1 for non-coding nucleotides and -3 for codons.  Must be negative and smaller than \fIGAP_PENALTY\fR to produce sensible alignments.
.TP
.BR \-\-illumina-hiseq
Sequences were generated by an Illumina HiSeq sequencer.
.TP
.BR \-\-illumina-miseq 
Sequences were generated by an Illumina MiSeq sequencer.
.TP
.BR \-\-illumina-hiseq
Sequences were generated by an Ion Torrent PGM sequencer.
.TP
.BR   \-\-pacbio
Sequences were generated by a Pacific Biosciences PacBio RS sequencer.
.TP
.BR   \-\-roche
Sequences were generated by a Roche/454 GS Junior sequencer.
.TP
.BR   \-\-sanger
Sequences were generated by Sanger sequencing.

.SH SEE ALSO
muscle(1), clustalw(1), bowtie(1)
.SH BUGS
No known bugs (beta version).
.SH AUTHOR
Imogen Wright (imogen@sanbi.ac.za)
